name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Start Deployment
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          version: 12
      - name: Setup yarn.
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
      - name: Install dependencies
        run: |
          yarn install
      - name: Deploy!
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          yarn run build && ./node_modules/.bin/firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"
